INSERT INTO [personagem] ([id],[nome],[jogador],[image_file],[att_intelecto],[att_aura],[att_carisma],[att_forca],[att_fisico],[att_agilidade],[att_percepcao],[defesa_ativa],[defesa_passiva],[energia_heroica_maxima],[energia_heroica],[energia_fisica],[absorcao],[raca],[profissao],[especializacao],[nivel],[pontos_habilidade],[pontos_combate],[pontos_arma],[pontos_magia],[altura],[peso],[idade],[olhos],[cabelo],[pele],[aparencia],[divindade],[classe_social],[local_nascimento],[historia],[moedas_cobre],[moedas_prata],[moedas_ouro]) VALUES (1,'Rosencrantz','Clever',NULL,0,0,0,0,0,0,0,NULL,NULL,NULL,NULL,NULL,NULL,1,6,NULL,4,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,'Livre',NULL,NULL,5,NULL,NULL);
INSERT INTO [personagem] ([id],[nome],[jogador],[image_file],[att_intelecto],[att_aura],[att_carisma],[att_forca],[att_fisico],[att_agilidade],[att_percepcao],[defesa_ativa],[defesa_passiva],[energia_heroica_maxima],[energia_heroica],[energia_fisica],[absorcao],[raca],[profissao],[especializacao],[nivel],[pontos_habilidade],[pontos_combate],[pontos_arma],[pontos_magia],[altura],[peso],[idade],[olhos],[cabelo],[pele],[aparencia],[divindade],[classe_social],[local_nascimento],[historia],[moedas_cobre],[moedas_prata],[moedas_ouro]) VALUES (2,'Guildenstern','Clever',NULL,1,1,1,1,1,1,1,NULL,NULL,NULL,NULL,NULL,NULL,1,2,NULL,4,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,7,NULL,NULL,NULL,5,NULL,NULL);
INSERT INTO [personagem] ([id],[nome],[jogador],[image_file],[att_intelecto],[att_aura],[att_carisma],[att_forca],[att_fisico],[att_agilidade],[att_percepcao],[defesa_ativa],[defesa_passiva],[energia_heroica_maxima],[energia_heroica],[energia_fisica],[absorcao],[raca],[profissao],[especializacao],[nivel],[pontos_habilidade],[pontos_combate],[pontos_arma],[pontos_magia],[altura],[peso],[idade],[olhos],[cabelo],[pele],[aparencia],[divindade],[classe_social],[local_nascimento],[historia],[moedas_cobre],[moedas_prata],[moedas_ouro]) VALUES (3,'Odin','Clever',NULL,3,2,2,1,2,1,1,NULL,NULL,NULL,NULL,NULL,NULL,1,1,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,10,NULL,NULL,NULL,5,NULL,NULL);
INSERT INTO [personagem] ([id],[nome],[jogador],[image_file],[att_intelecto],[att_aura],[att_carisma],[att_forca],[att_fisico],[att_agilidade],[att_percepcao],[defesa_ativa],[defesa_passiva],[energia_heroica_maxima],[energia_heroica],[energia_fisica],[absorcao],[raca],[profissao],[especializacao],[nivel],[pontos_habilidade],[pontos_combate],[pontos_arma],[pontos_magia],[altura],[peso],[idade],[olhos],[cabelo],[pele],[aparencia],[divindade],[classe_social],[local_nascimento],[historia],[moedas_cobre],[moedas_prata],[moedas_ouro]) VALUES (4,'Myau','Clever',NULL,1,1,1,1,1,1,1,NULL,NULL,NULL,NULL,NULL,NULL,5,4,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,12,NULL,NULL,NULL,5,NULL,NULL);
INSERT INTO [personagem] ([id],[nome],[jogador],[image_file],[att_intelecto],[att_aura],[att_carisma],[att_forca],[att_fisico],[att_agilidade],[att_percepcao],[defesa_ativa],[defesa_passiva],[energia_heroica_maxima],[energia_heroica],[energia_fisica],[absorcao],[raca],[profissao],[especializacao],[nivel],[pontos_habilidade],[pontos_combate],[pontos_arma],[pontos_magia],[altura],[peso],[idade],[olhos],[cabelo],[pele],[aparencia],[divindade],[classe_social],[local_nascimento],[historia],[moedas_cobre],[moedas_prata],[moedas_ouro]) VALUES (5,'Noah','Clever',NULL,1,1,1,1,1,1,1,NULL,NULL,NULL,NULL,NULL,NULL,2,3,NULL,2,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,2,NULL,NULL,NULL,5,NULL,NULL);
INSERT INTO [personagem] ([id],[nome],[jogador],[image_file],[att_intelecto],[att_aura],[att_carisma],[att_forca],[att_fisico],[att_agilidade],[att_percepcao],[defesa_ativa],[defesa_passiva],[energia_heroica_maxima],[energia_heroica],[energia_fisica],[absorcao],[raca],[profissao],[especializacao],[nivel],[pontos_habilidade],[pontos_combate],[pontos_arma],[pontos_magia],[altura],[peso],[idade],[olhos],[cabelo],[pele],[aparencia],[divindade],[classe_social],[local_nascimento],[historia],[moedas_cobre],[moedas_prata],[moedas_ouro]) VALUES (6,'Alis','Clever',NULL,0,3,0,2,2,1,2,NULL,NULL,NULL,NULL,NULL,NULL,3,5,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,4,NULL,NULL,NULL,5,NULL,NULL);
INSERT INTO [personagem] ([id],[nome],[jogador],[image_file],[att_intelecto],[att_aura],[att_carisma],[att_forca],[att_fisico],[att_agilidade],[att_percepcao],[defesa_ativa],[defesa_passiva],[energia_heroica_maxima],[energia_heroica],[energia_fisica],[absorcao],[raca],[profissao],[especializacao],[nivel],[pontos_habilidade],[pontos_combate],[pontos_arma],[pontos_magia],[altura],[peso],[idade],[olhos],[cabelo],[pele],[aparencia],[divindade],[classe_social],[local_nascimento],[historia],[moedas_cobre],[moedas_prata],[moedas_ouro]) VALUES (7,'Thorin','joão',NULL,0,0,0,0,0,0,0,NULL,NULL,NULL,NULL,NULL,NULL,3,1,NULL,5,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,8,NULL,NULL,NULL,5,NULL,NULL);
INSERT INTO [personagem] ([id],[nome],[jogador],[image_file],[att_intelecto],[att_aura],[att_carisma],[att_forca],[att_fisico],[att_agilidade],[att_percepcao],[defesa_ativa],[defesa_passiva],[energia_heroica_maxima],[energia_heroica],[energia_fisica],[absorcao],[raca],[profissao],[especializacao],[nivel],[pontos_habilidade],[pontos_combate],[pontos_arma],[pontos_magia],[altura],[peso],[idade],[olhos],[cabelo],[pele],[aparencia],[divindade],[classe_social],[local_nascimento],[historia],[moedas_cobre],[moedas_prata],[moedas_ouro]) VALUES (8,'Tanagrim','Clever',NULL,1,1,2,0,1,2,1,6,5,19,19,18,20,1,1,2,1,14,7,7,0,185,80,26,'pretos','preto','clara','Bruto.',1,'Livre',2,'Saiu por aí até chegar lá.',1,2,0);
INSERT INTO [personagem] ([id],[nome],[jogador],[image_file],[att_intelecto],[att_aura],[att_carisma],[att_forca],[att_fisico],[att_agilidade],[att_percepcao],[defesa_ativa],[defesa_passiva],[energia_heroica_maxima],[energia_heroica],[energia_fisica],[absorcao],[raca],[profissao],[especializacao],[nivel],[pontos_habilidade],[pontos_combate],[pontos_arma],[pontos_magia],[altura],[peso],[idade],[olhos],[cabelo],[pele],[aparencia],[divindade],[classe_social],[local_nascimento],[historia],[moedas_cobre],[moedas_prata],[moedas_ouro]) VALUES (9,'Timothy','Clever',NULL,2,3,1,0,0,1,1,6,5,6,6,12,16,1,4,22,1,12,5,4,7,177,72,17,'pretos','preto','clara','Franzino.',1,'Livre',1,'Estuda as artes mágicas.',4,1,0);

INSERT INTO [personagem_habilidade_especializacao] ([id],[id_personagem],[id_habilidade],[id_habilidade_especializacao],[especializacao],[nivel]) VALUES (1,9,22,19,'Comum',1);
INSERT INTO [personagem_habilidade_especializacao] ([id],[id_personagem],[id_habilidade],[id_habilidade_especializacao],[especializacao],[nivel]) VALUES (2,9,22,18,'Élfico',1);

INSERT INTO [personagem_equipamento] ([id_personagem],[id_equipamento],[quantidade]) VALUES (8,225,1);
INSERT INTO [personagem_equipamento] ([id_personagem],[id_equipamento],[quantidade]) VALUES (8,233,1);
INSERT INTO [personagem_equipamento] ([id_personagem],[id_equipamento],[quantidade]) VALUES (8,236,1);
INSERT INTO [personagem_equipamento] ([id_personagem],[id_equipamento],[quantidade]) VALUES (9,225,1);
INSERT INTO [personagem_equipamento] ([id_personagem],[id_equipamento],[quantidade]) VALUES (9,233,1);
INSERT INTO [personagem_equipamento] ([id_personagem],[id_equipamento],[quantidade]) VALUES (9,236,1);

INSERT INTO [personagem_habilidade] ([id_personagem],[id_habilidade],[nivel]) VALUES (8,1,1);
INSERT INTO [personagem_habilidade] ([id_personagem],[id_habilidade],[nivel]) VALUES (9,1,1);

INSERT INTO [personagem_combate] ([id_personagem],[id_combate],[nivel]) VALUES (9,4,1);

INSERT INTO [personagem_magia] ([id_personagem],[id_magia],[nivel]) VALUES (9,1,1);
INSERT INTO [personagem_magia] ([id_personagem],[id_magia],[nivel]) VALUES (9,2,1);
INSERT INTO [personagem_magia] ([id_personagem],[id_magia],[nivel]) VALUES (9,3,1);

