from PyQt5 import QtCore, QtGui, QtWidgets
from resources.categoria import *
from PyQt5.QtWidgets import *
#class animItemWidget(QtGui.QWidget):


class CombateDefault(QWidget):
    def _init_(self, parent=None):
        QWidget.__init__(self, parent=parent)
        #Form.setObjectName("Form")
        #Form.resize(413, 33)
        self.txtAjuste = QtWidgets.QLineEdit(Form)
        self.txtAjuste.setEnabled(True)
        self.txtAjuste.setGeometry(QtCore.QRect(207, 6, 50, 22))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.txtAjuste.setFont(font)
        self.txtAjuste.setStyleSheet("background-color: rgb(240, 240, 240);")
        self.txtAjuste.setAlignment(QtCore.Qt.AlignCenter)
        self.txtAjuste.setReadOnly(True)
        self.txtAjuste.setObjectName("txtAjuste")
        self.lblIcone = QtWidgets.QLabel(Form)
        self.lblIcone.setGeometry(QtCore.QRect(385, 7, 21, 21))
        self.lblIcone.setText("")
        self.lblIcone.setPixmap(QtGui.QPixmap(""))
        self.lblIcone.setScaledContents(True)
        self.lblIcone.setObjectName("lblIcone")
        self.txtCusto = QtWidgets.QLineEdit(Form)
        self.txtCusto.setEnabled(True)
        self.txtCusto.setGeometry(QtCore.QRect(155, 6, 50, 22))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.txtCusto.setFont(font)
        self.txtCusto.setStyleSheet("background-color: rgb(240, 240, 240);")
        self.txtCusto.setAlignment(QtCore.Qt.AlignCenter)
        self.txtCusto.setReadOnly(True)
        self.txtCusto.setObjectName("txtCusto")
        self.txtCategoria = QtWidgets.QLineEdit(Form)
        self.txtCategoria.setEnabled(True)
        self.txtCategoria.setGeometry(QtCore.QRect(312, 6, 70, 22))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.txtCategoria.setFont(font)
        self.txtCategoria.setStyleSheet("background-color: rgb(240, 240, 240);")
        self.txtCategoria.setAlignment(QtCore.Qt.AlignCenter)
        self.txtCategoria.setReadOnly(True)
        self.txtCategoria.setObjectName("txtCategoria")
        self.txtdescricao = QtWidgets.QLabel(Form)
        self.txtdescricao.setGeometry(QtCore.QRect(5, 7, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(6)
        font.setBold(True)
        font.setWeight(75)
        self.txtdescricao.setFont(font)
        self.txtdescricao.setObjectName("txtdescricao")
        self.txtTotal = QtWidgets.QLineEdit(Form)
        self.txtTotal.setEnabled(True)
        self.txtTotal.setGeometry(QtCore.QRect(260, 6, 50, 22))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.txtTotal.setFont(font)
        self.txtTotal.setStyleSheet("background-color: rgb(240, 240, 240);")
        self.txtTotal.setText("")
        self.txtTotal.setAlignment(QtCore.Qt.AlignCenter)
        self.txtTotal.setReadOnly(True)
        self.txtTotal.setObjectName("txtTotal")
        self.spnNivel = QtWidgets.QSpinBox(Form)
        self.spnNivel.setGeometry(QtCore.QRect(103, 6, 50, 22))
        self.spnNivel.setAlignment(QtCore.Qt.AlignCenter)
        self.spnNivel.setObjectName("spnNivel")

        #self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(self)

    #def retranslateUi(self, Form):
    #    _translate = QtCore.QCoreApplication.translate
    #    #Form.setWindowTitle(_translate("Form", "Form"))

    #    self.setWindowTitle(_translate("Form", "Form"))
    #    self.txtAjuste.setText(_translate("Form", "..."))
    #    self.txtCusto.setText(_translate("Form", "..."))
    #    self.txtCategoria.setText(_translate("Form", "..."))
    #    self.txtdescricao.setText(_translate("Form", "..."))


#if __name__ == "__main__":
#    import sys
#    app = QtWidgets.QApplication(sys.argv)
#    Form = QtWidgets.QWidget()
#    ui = Ui_Form()
#    ui.setupUi(Form)
#    Form.show()
#    sys.exit(app.exec_())
